### ISSUE TITLE
Could this be used in Lenovo Legion 5 (not pro)?

### ISSUE THREAD

**Issue by lucidtyper** [maniac103/lenovo-kbd-backlight#1]
Hey there. 

I'm looking for a code like yours to make my keyboard backlight change it colour from the default ones. Would it be possible to run this on a Lenovo Legion 5? I've done everything you say in the README.md but nothing changes... 

I'm looking for an answer. Thanks for your time!

**Comment by maniac103** [comment]
Does the non-pro one also have a 4-zone keyboard? What's the keyboard's USB product ID? For the latter, please provide the output of `lsusb`.

**Comment by lucidtyper** [comment]
Yes, at least mine has a 4-zone keyboard. I don't know how to find the ID of the keyboard, but I'll leave here the output of lsusb and xinput

The lsusb output shows this:
```
Bus 004 Device 002: ID 05e3:0620 Genesys Logic, Inc. USB3.2 Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 048d:c100 Integrated Technology Express, Inc. ITE Device(8910)
Bus 003 Device 003: ID 8087:0029 Intel Corp. AX200 Bluetooth
Bus 003 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 048d:c955 Integrated Technology Express, Inc. ITE Device(8295)
Bus 001 Device 002: ID 174f:244c Syntek Integrated Camera
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

The xinput command throws this output:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ITE Tech. Inc. ITE Device(8910) Keyboard	id=12	[slave  pointer  (2)]
⎜   ↳ MSFT0001:00 06CB:7F28 Mouse             	id=15	[slave  pointer  (2)]
⎜   ↳ MSFT0001:00 06CB:7F28 Touchpad          	id=16	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=10	[slave  keyboard (3)]
    ↳ ITE Tech. Inc. ITE Device(8295) Keyboard	id=11	[slave  keyboard (3)]
    ↳ ITE Tech. Inc. ITE Device(8910) Wireless Radio Control	id=13	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=14	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=17	[slave  keyboard (3)]
    ↳ ITE Tech. Inc. ITE Device(8910) Keyboard	id=18	[slave  keyboard (3)]
```

**Comment by maniac103** [comment]
`Bus 001 Device 003: ID 048d:c955 Integrated Technology Express, Inc. ITE Device(8295)`

This is different from mine, which is `048d:c965`. You can try to adapt the USB PID [here](https://github.com/maniac103/lenovo-kbd-backlight/blob/master/service/kbd_bl_api.py#L10) and hope for the best.

**Comment by lucidtyper** [comment]
Alrighty. I'll try this as soon I can get to my laptop. Thanks for the quick answer!

**Comment by lucidtyper** [comment]
> `Bus 001 Device 003: ID 048d:c955 Integrated Technology Express, Inc. ITE Device(8295)`
> 
> This is different from mine, which is `048d:c965`. You can try to adapt the USB PID [here](https://github.com/maniac103/lenovo-kbd-backlight/blob/master/service/kbd_bl_api.py#L10) and hope for the best.

Nothing but several errors on journalctl and systemctl...

Journal says that the code exited with exit status as 1.

Systemctl on the other hand...:
```
× lenovo-kbd-backlight.service - Lenovo keyboard backlight service
     Loaded: loaded (/etc/systemd/system/lenovo-kbd-backlight.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-10-12 15:35:10 CEST; 2min 46s ago
    Process: 3034 ExecStart=/usr/local/bin/lenovo-kbd-backlight-service /etc/lenovo-kbd-backlight.cfg (code=exited, status=1/FAILURE)
   Main PID: 3034 (code=exited, status=1/FAILURE)
        CPU: 60ms

oct 12 15:35:10 linux-legion-5 systemd[1]: lenovo-kbd-backlight.service: Scheduled restart job, restart counter is at 5.
oct 12 15:35:10 linux-legion-5 systemd[1]: Stopped Lenovo keyboard backlight service.
oct 12 15:35:10 linux-legion-5 systemd[1]: lenovo-kbd-backlight.service: Start request repeated too quickly.
oct 12 15:35:10 linux-legion-5 systemd[1]: lenovo-kbd-backlight.service: Failed with result 'exit-code'.
oct 12 15:35:10 linux-legion-5 systemd[1]: Failed to start Lenovo keyboard backlight service.

```

**Comment by EllaFoxo** [comment]
Can confirm, this works with `048d:c955` on the Lenovo Legion 5i as well. Thank you so much <3

Ran the tool from the command line and noticed the issues (systemd report was extremely vague). Turns out for me it was just package reference issues. Would be nice if we could get some instructions to use with python-pip.

**Comment by maniac103** [comment]
> Can confirm, this works with 048d:c955 on the Lenovo Legion 5i as well. Thank you so much <3

Nice. I'll add that second PID to the check.

> Turns out for me it was just package reference issues. Would be nice if we could get some instructions to use with python-pip

What reference issues do you mean?
I'm by no means a Python expert (this was my first Python project), but I thought setuptools will take care of installing the dependencies ... is that not the case?

**Comment by EllaFoxo** [comment]
Nah, it does install dependencies. I'm just having issues when installing the script. I'm no python expert either. I'll open a separate issue for it when I find the time

**Comment by Theluga** [comment]
Hello, I know this is an old thread but I am having the exact same problems

I solved the install problem with:

`PYTHONPATH=/usr/local/lib/python3.11/site-packages/ sudo bash -c "python3 setup.py install --prefix=/usr/local"`

but the systemd services continues to give error:

> Loaded: loaded (/etc/systemd/system/lenovo-kbd-backlight.service; enabled; preset: disabled)
>      Active: failed (Result: exit-code) since Sun 2024-01-07 21:10:58 -03; 2s ago
>     Process: 5426 ExecStart=/usr/local/bin/lenovo-kbd-backlight-service /etc/lenovo-kbd-backlight.cfg (code=exited, sta>
>    Main PID: 5426 (code=exited, status=1/FAILURE)
>         CPU: 42ms
> 
> Jan 07 21:10:58 lugathe systemd[1]: lenovo-kbd-backlight.service: Scheduled restart job, restart counter is at 5.
> Jan 07 21:10:58 lugathe systemd[1]: lenovo-kbd-backlight.service: Start request repeated too quickly.
> Jan 07 21:10:58 lugathe systemd[1]: lenovo-kbd-backlight.service: Failed with result 'exit-code'.
> Jan 07 21:10:58 lugathe systemd[1]: Failed to start Lenovo keyboard backlight service.


Then I tried executing the scripts this way:

`PYTHONPATH="/usr/local/lib/python3.11/site-packages/" sudo bash -c "/usr/local/bin/lenovo-kbd-backlight-service /etc/lenovo-kbd-backlight.cfg"`

but I get:

> Traceback (most recent call last):
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
>     return next(cls.discover(name=name))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/lenovo-kbd-backlight-service", line 33, in <module>
>     sys.exit(load_entry_point('lenovo-kbd-backlight-service==0.1.0', 'console_scripts', 'lenovo-kbd-backlight-service')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/lenovo-kbd-backlight-service", line 22, in importlib_load_entry_point
>     for entry_point in distribution(dist_name).entry_points
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
>     return Distribution.from_name(distribution_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for lenovo-kbd-backlight-service
> 

I don't know what I am doing wrong, I just followed the instructions and tried to debug the errors it was given...

I don't know if it helps but I am running Arch Linux with gnome, My laptop is an Ideapad Gaming 3, and I modified the script to 048d:c966 to see if it would work but I am having the same problem and python is not my fort. Sorry for the inconvenience

Thanks!.
